# Generated by Django 5.0.3 on 2024-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='NIN',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='sitter',
            name='NoK',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sitter',
            name='contact',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='sitter',
            name='dob',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='sitter',
            name='education',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='sitter',
            name='recoName',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='sitter',
            name='sitterNum',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
