# Generated by Django 5.0.3 on 2024-04-24 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0002_sitter_nin_sitter_nok_sitter_contact_sitter_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='dob',
        ),
    ]
