# Generated by Django 5.0.3 on 2024-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0003_remove_sitter_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='sitterNum',
            field=models.IntegerField(default=0),
        ),
    ]
